version: '3.9'
services:
  dev:
    container_name: fastapi-yt-predictor
    build:
      image: kshgrk/yt-category-predictor-fastapi:0.1 
      context: .
        #    stdin_open: true # docker run -i
        #     tty: true # docker run -t
    ports:
      - 8000:8000

